### ISSUE TITLE
The project can't start correctly

### ISSUE THREAD

**Issue by zhangchunsheng** [RotaNova/isc#1]
rotanava-boot-module-basedata_1          | 16:06:06,383 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Log destination 192.168.0.167:4560: connection failed. java.net.SocketTimeoutException: connect timed out
rotanava-boot-module-basedata_1          |      at java.net.SocketTimeoutException: connect timed out
rotanava-boot-module-basedata_1          |      at      at java.net.PlainSocketImpl.socketConnect(Native Method)
rotanava-boot-module-basedata_1          |      at      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
rotanava-boot-module-basedata_1          |      at      at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
rotanava-boot-module-basedata_1          |      at      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
rotanava-boot-module-basedata_1          |      at      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
rotanava-boot-module-basedata_1          |      at      at java.net.Socket.connect(Socket.java:589)
rotanava-boot-module-basedata_1          |      at      at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.openSocket(AbstractLogstashTcpSocketAppender.java:718)
rotanava-boot-module-basedata_1          |      at      at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.onStart(AbstractLogstashTcpSocketAppender.java:638)
rotanava-boot-module-basedata_1          |      at      at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onStart(AsyncDisruptorAppender.java:351)
rotanava-boot-module-basedata_1          |      at      at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.notifyStart(BatchEventProcessor.java:224)
rotanava-boot-module-basedata_1          |      at      at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:120)
rotanava-boot-module-basedata_1          |      at      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
rotanava-boot-module-basedata_1          |      at      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
rotanava-boot-module-basedata_1          |      at      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
rotanava-boot-module-basedata_1          |      at      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
rotanava-boot-module-basedata_1          |      at      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
rotanava-boot-module-basedata_1          |      at      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
rotanava-boot-module-basedata_1          |      at      at java.lang.Thread.run(Thread.java:748)
rotanava-boot-module-basedata_1          | 2022-12-28 16:06:06.398  INFO 1 --- [           main] e.

**Comment by asmoyou** [comment]
This warning will not stop startup of the service, you have two options to fix it:
① Close the log service[Logstash];
② Configure your own correct log collection server.
Or, you just ignore it.
